spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/url_shortner
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true

--- ################################################################################################
spring:
  config:
    activate.on-profile: integration-test
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
